# Generated by Django 4.2.11 on 2024-06-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_extrainfos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraInfos',
        ),
    ]
